# Generated by Django 3.2.4 on 2021-06-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquete', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paquete',
            name='order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
